language: ruby
script: rspec
services: mongodb
rvm:
  - 1.9.3
  - 2.0.0
gemfile:
  - gemfiles/active_record/3-0.gemfile
  - gemfiles/active_record/3-1.gemfile
  - gemfiles/active_record/3-2.gemfile
  - gemfiles/active_record/4-0.gemfile
  - gemfiles/mongo_mapper/0-9.gemfile
  - gemfiles/mongo_mapper/0-10.gemfile
  - gemfiles/mongo_mapper/0-11.gemfile
  - gemfiles/mongo_mapper/0-12.gemfile
  - gemfiles/mongoid/2-0.gemfile
  - gemfiles/mongoid/2-1.gemfile
  - gemfiles/mongoid/2-2.gemfile
  - gemfiles/mongoid/2-3.gemfile
  - gemfiles/mongoid/2-4.gemfile
  - gemfiles/mongoid/2-5.gemfile
  - gemfiles/mongoid/2-6.gemfile
  - gemfiles/mongoid/3-0.gemfile
  - gemfiles/mongoid/3-1.gemfile
  - gemfiles/data_mapper/1-0.gemfile
  - gemfiles/data_mapper/1-1.gemfile
  - gemfiles/data_mapper/1-2.gemfile
matrix:
  include:
    - rvm: 2.0.0
      gemfile: Gemfile
      script: rake
